services:
  safeguards:
    build: ./
    image: saigautham7/safe-guard-spring
    ports:
     - '8080:8080'
    depends_on:
      - postgres
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '1'
          memory: 256M
        reservations:
          memory: 256M

  postgres:
    image: postgres
#    cap_add:
#      - NET_ADMIN
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: Gautham
      POSTGRES_PASSWORD: Root@123
    ports:
      - "5432:5432"
    restart: always
